kind: pipeline
name: deploy_website

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: darkblue.llc
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build ksp-website
